sudo: false
language: python
python:
    - "3.5"
    - "3.4"
    - "3.3"
    - "pypy3"
install: "pip install --allow-external ipaddr --allow-unverified ipaddr -e .[test]"
script: make test
before_install:
    pip install codecov
after_success:
    codecov
